# Generated by Django 4.0 on 2022-01-02 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Магазин')),
                ('number', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Найменування')),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('CO_code', models.IntegerField(blank=True, default=1000)),
                ('barcode', models.BigIntegerField(blank=True, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.shop')),
            ],
        ),
    ]
